In [78]:
import pandas as pd

df = pd.read_csv("weather_madrid_1997_2015.csv")
df

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees
0,1997-1-1,7.0,4.0,2.0,5.0,3.0,2.0,100.0,95.0,76.0,...,10.0,9.0,4.0,13,6,NaN,0.00,6.0,NaN,229
1,1997-1-2,7.0,3.0,0.0,6.0,3.0,0.0,100.0,92.0,71.0,...,10.0,9.0,4.0,26,8,47.0,0.00,5.0,Rain,143
2,1997-1-3,5.0,3.0,2.0,5.0,1.0,-1.0,100.0,85.0,70.0,...,10.0,10.0,7.0,27,19,NaN,0.00,6.0,Rain-Snow,256
3,1997-1-4,7.0,3.0,-1.0,-2.0,-3.0,-4.0,86.0,63.0,49.0,...,10.0,10.0,10.0,27,19,40.0,0.00,2.0,NaN,284
4,1997-1-5,2.0,0.0,-1.0,2.0,0.0,-3.0,100.0,95.0,86.0,...,10.0,5.0,1.0,14,6,NaN,0.00,7.0,Snow,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,2015-12-27,14.0,7.0,-1.0,6.0,2.0,-2.0,100.0,77.0,30.0,...,31.0,14.0,5.0,14,6,NaN,0.00,8.0,Fog,38
6808,2015-12-28,15.0,8.0,2.0,8.0,4.0,1.0,100.0,78.0,34.0,...,31.0,14.0,8.0,27,8,45.0,0.51,7.0,Rain,243
6809,2015-12-29,11.0,8.0,5.0,9.0,7.0,5.0,100.0,89.0,66.0,...,31.0,9.0,0.0,14,8,32.0,2.03,5.0,Fog-Rain,190
6810,2015-12-30,9.0,8.0,6.0,7.0,6.0,5.0,93.0,87.0,70.0,...,19.0,10.0,6.0,14,5,34.0,0.00,6.0,NaN,256
6811,2015-12-31,12.0,10.0,7.0,10.0,8.0,7.0,100.0,90.0,70.0,...,31.0,8.0,2.0,14,6,NaN,0.25,6.0,Rain,313

In [79]:
def quitarcolumnas(*x):
    
    return df.drop(list(x),axis = 1)

df =quitarcolumnas(' Max Gust SpeedKm/h'," CloudCover",'Precipitationmm'," Mean Sea Level PressurehPa",'WindDirDegrees', ' Max Sea Level PressurehPa',' Min Sea Level PressurehPa','Dew PointC', 'MeanDew PointC', 'Min DewpointC',' Events')

In [80]:
df.columns

Index(['CET', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC',
       'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max VisibilityKm',
       ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h',
       ' Mean Wind SpeedKm/h'],
      dtype='object')

In [81]:
def renamecolumnas(x):
    
    return df.rename(columns=x)
df =renamecolumnas({'Max TemperatureC':'Max Temp','Mean TemperatureC': 'Mean Temp','Min TemperatureC':'Min Temp','Max Humidity': 'Max Hum',' Mean Humidity':'Mean Hum',' Min Humidity':'Min Hum',' Max VisibilityKm': 'Max Vis Km',' Mean VisibilityKm':'Mean Vis Km',' Min VisibilitykM': 'Min Vis Km',' Max Wind SpeedKm/h':'Max Wind Km/h',' Mean Wind SpeedKm/h': 'Mean Wind Kmh'})

In [82]:
d=df.head(32)

In [83]:
# aÃ±os bisiestos 2000,2004,2008,2012,2016
# 181 dias hasta junio
#sustituir 181 por 1997 junio
# 184 dias hasta diciembre
#d =d.groupby(["CET"]).mean
df.dtypes

CET               object
Max Temp         float64
Mean Temp        float64
Min Temp         float64
Max Hum          float64
Mean Hum         float64
Min Hum          float64
Max Vis Km       float64
Mean Vis Km      float64
Min Vis Km       float64
Max Wind Km/h      int64
Mean Wind Kmh      int64
dtype: object

In [84]:
df["CET"]=pd.to_datetime(df["CET"])

In [85]:
df.dtypes

CET              datetime64[ns]
Max Temp                float64
Mean Temp               float64
Min Temp                float64
Max Hum                 float64
Mean Hum                float64
Min Hum                 float64
Max Vis Km              float64
Mean Vis Km             float64
Min Vis Km              float64
Max Wind Km/h             int64
Mean Wind Kmh             int64
dtype: object

In [86]:
df

,CET,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1997-01-01,7.0,4.0,2.0,100.0,95.0,76.0,10.0,9.0,4.0,13,6
1,1997-01-02,7.0,3.0,0.0,100.0,92.0,71.0,10.0,9.0,4.0,26,8
2,1997-01-03,5.0,3.0,2.0,100.0,85.0,70.0,10.0,10.0,7.0,27,19
3,1997-01-04,7.0,3.0,-1.0,86.0,63.0,49.0,10.0,10.0,10.0,27,19
4,1997-01-05,2.0,0.0,-1.0,100.0,95.0,86.0,10.0,5.0,1.0,14,6
...,...,...,...,...,...,...,...,...,...,...,...,...
6807,2015-12-27,14.0,7.0,-1.0,100.0,77.0,30.0,31.0,14.0,5.0,14,6
6808,2015-12-28,15.0,8.0,2.0,100.0,78.0,34.0,31.0,14.0,8.0,27,8
6809,2015-12-29,11.0,8.0,5.0,100.0,89.0,66.0,31.0,9.0,0.0,14,8
6810,2015-12-30,9.0,8.0,6.0,93.0,87.0,70.0,19.0,10.0,6.0,14,5
6811,2015-12-31,12.0,10.0,7.0,100.0,90.0,70.0,31.0,8.0,2.0,14,6

In [87]:
df['day'] = df['CET'].dt.day
df['month'] = df['CET'].dt.month
df['year'] = df['CET'].dt.year

In [88]:
print(df.isna().sum())
df.columns

CET                0
Max Temp           2
Mean Temp          3
Min Temp           2
Max Hum            2
Mean Hum           2
Min Hum            2
Max Vis Km       940
Mean Vis Km      940
Min Vis Km       940
Max Wind Km/h      0
Mean Wind Kmh      0
day                0
month              0
year               0
dtype: int64

Index(['CET', 'Max Temp', 'Mean Temp', 'Min Temp', 'Max Hum', 'Mean Hum',
       'Min Hum', 'Max Vis Km', 'Mean Vis Km', 'Min Vis Km', 'Max Wind Km/h',
       'Mean Wind Kmh', 'day', 'month', 'year'],
      dtype='object')

In [89]:
df =quitarcolumnas("CET")

In [90]:
df

,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh,day,month,year
0,7.0,4.0,2.0,100.0,95.0,76.0,10.0,9.0,4.0,13,6,1,1,1997
1,7.0,3.0,0.0,100.0,92.0,71.0,10.0,9.0,4.0,26,8,2,1,1997
2,5.0,3.0,2.0,100.0,85.0,70.0,10.0,10.0,7.0,27,19,3,1,1997
3,7.0,3.0,-1.0,86.0,63.0,49.0,10.0,10.0,10.0,27,19,4,1,1997
4,2.0,0.0,-1.0,100.0,95.0,86.0,10.0,5.0,1.0,14,6,5,1,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,14.0,7.0,-1.0,100.0,77.0,30.0,31.0,14.0,5.0,14,6,27,12,2015
6808,15.0,8.0,2.0,100.0,78.0,34.0,31.0,14.0,8.0,27,8,28,12,2015
6809,11.0,8.0,5.0,100.0,89.0,66.0,31.0,9.0,0.0,14,8,29,12,2015
6810,9.0,8.0,6.0,93.0,87.0,70.0,19.0,10.0,6.0,14,5,30,12,2015
6811,12.0,10.0,7.0,100.0,90.0,70.0,31.0,8.0,2.0,14,6,31,12,2015

In [91]:
lista =['day', 'month', 'year','Max Temp', 'Mean Temp', 'Min Temp', 'Max Hum', 'Mean Hum','Min Hum', 'Max Vis Km', 'Mean Vis Km', 'Min Vis Km', 'Max Wind Km/h','Mean Wind Kmh']
df =df[lista]
df

,day,month,year,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1,1,1997,7.0,4.0,2.0,100.0,95.0,76.0,10.0,9.0,4.0,13,6
1,2,1,1997,7.0,3.0,0.0,100.0,92.0,71.0,10.0,9.0,4.0,26,8
2,3,1,1997,5.0,3.0,2.0,100.0,85.0,70.0,10.0,10.0,7.0,27,19
3,4,1,1997,7.0,3.0,-1.0,86.0,63.0,49.0,10.0,10.0,10.0,27,19
4,5,1,1997,2.0,0.0,-1.0,100.0,95.0,86.0,10.0,5.0,1.0,14,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,27,12,2015,14.0,7.0,-1.0,100.0,77.0,30.0,31.0,14.0,5.0,14,6
6808,28,12,2015,15.0,8.0,2.0,100.0,78.0,34.0,31.0,14.0,8.0,27,8
6809,29,12,2015,11.0,8.0,5.0,100.0,89.0,66.0,31.0,9.0,0.0,14,8
6810,30,12,2015,9.0,8.0,6.0,93.0,87.0,70.0,19.0,10.0,6.0,14,5
6811,31,12,2015,12.0,10.0,7.0,100.0,90.0,70.0,31.0,8.0,2.0,14,6

In [92]:
#quitarme los 29 de febrero

dropcols = df[(df['day']== 29) & (df['month']==2)]
dropcols.index
df =df.drop(dropcols.index)
df

,day,month,year,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1,1,1997,7.0,4.0,2.0,100.0,95.0,76.0,10.0,9.0,4.0,13,6
1,2,1,1997,7.0,3.0,0.0,100.0,92.0,71.0,10.0,9.0,4.0,26,8
2,3,1,1997,5.0,3.0,2.0,100.0,85.0,70.0,10.0,10.0,7.0,27,19
3,4,1,1997,7.0,3.0,-1.0,86.0,63.0,49.0,10.0,10.0,10.0,27,19
4,5,1,1997,2.0,0.0,-1.0,100.0,95.0,86.0,10.0,5.0,1.0,14,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,27,12,2015,14.0,7.0,-1.0,100.0,77.0,30.0,31.0,14.0,5.0,14,6
6808,28,12,2015,15.0,8.0,2.0,100.0,78.0,34.0,31.0,14.0,8.0,27,8
6809,29,12,2015,11.0,8.0,5.0,100.0,89.0,66.0,31.0,9.0,0.0,14,8
6810,30,12,2015,9.0,8.0,6.0,93.0,87.0,70.0,19.0,10.0,6.0,14,5
6811,31,12,2015,12.0,10.0,7.0,100.0,90.0,70.0,31.0,8.0,2.0,14,6

In [93]:
#sustituir si es < que 6 por 1 y si es mayor que 6 > por 2
# bins y concatenate
df.dtypes

day                int64
month              int64
year               int64
Max Temp         float64
Mean Temp        float64
Min Temp         float64
Max Hum          float64
Mean Hum         float64
Min Hum          float64
Max Vis Km       float64
Mean Vis Km      float64
Min Vis Km       float64
Max Wind Km/h      int64
Mean Wind Kmh      int64
dtype: object

In [94]:
cutoffs = [0,6,12]
mpg_labels = ['1', '2']
bins = pd.cut(df['month'],cutoffs, labels=mpg_labels)
df["semester"] = bins
df

,day,month,year,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh,semester
0,1,1,1997,7.0,4.0,2.0,100.0,95.0,76.0,10.0,9.0,4.0,13,6,1
1,2,1,1997,7.0,3.0,0.0,100.0,92.0,71.0,10.0,9.0,4.0,26,8,1
2,3,1,1997,5.0,3.0,2.0,100.0,85.0,70.0,10.0,10.0,7.0,27,19,1
3,4,1,1997,7.0,3.0,-1.0,86.0,63.0,49.0,10.0,10.0,10.0,27,19,1
4,5,1,1997,2.0,0.0,-1.0,100.0,95.0,86.0,10.0,5.0,1.0,14,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,27,12,2015,14.0,7.0,-1.0,100.0,77.0,30.0,31.0,14.0,5.0,14,6,2
6808,28,12,2015,15.0,8.0,2.0,100.0,78.0,34.0,31.0,14.0,8.0,27,8,2
6809,29,12,2015,11.0,8.0,5.0,100.0,89.0,66.0,31.0,9.0,0.0,14,8,2
6810,30,12,2015,9.0,8.0,6.0,93.0,87.0,70.0,19.0,10.0,6.0,14,5,2
6811,31,12,2015,12.0,10.0,7.0,100.0,90.0,70.0,31.0,8.0,2.0,14,6,2

In [95]:
def groupBy(df,columns):
    return (df.groupby(columns).sum())

df =groupBy(df,["year","semester"])

In [96]:
df

                day  month  Max Temp  Mean Temp  Min Temp  Max Hum  Mean Hum  \
year semester
1997 1         2824    635    3622.0     2471.0    1413.0  15986.0   11966.0
     2         2914   1747    4349.0     3227.0    2184.0  14688.0   10886.0
1998 1         2824    635    3378.0     2259.0    1239.0  16016.0   11623.0
     2         2914   1747    4326.0     3054.0    1851.0  14365.0   10341.0
1999 1         2824    635    3394.0     2185.0    1056.0  15333.0   10484.0
     2         2914   1747    4093.0     3017.0    2020.0  14677.0   10889.0
2000 1         1660    347    1974.0     1267.0     607.0   8972.0    6761.0
     2         2533   1603    3555.0     2500.0    1580.0  13483.0    9732.0
2001 1         2824    635    3214.0     2173.0    1215.0  15377.0   11244.0
     2         2914   1747    3977.0     2766.0    1647.0  14322.0   10358.0
2002 1         2824    635    3333.0     2186.0    1117.0  15762.0   11378.0
     2         2914   1747    4032.0     2986.0    2004.0  15176.0   11365.0
2003 1         2824    635    3400.0     2292.0    1262.0  15438.0   11065.0
     2         2914   1747    4146.0     3056.0    2036.0  14338.0   10653.0
2004 1         2329    605    2794.0     1879.0    1023.0  12964.0    9381.0
     2         2914   1747    4282.0     3071.0    1923.0  14176.0   10090.0
2005 1         2824    635    3526.0     2253.0    1070.0  13818.0    9485.0
     2         2914   1747    4210.0     3027.0    1907.0  13200.0    9561.0
2006 1         2824    635    3459.0     2286.0    1200.0  14973.0   10626.0
     2         2914   1747    4357.0     3199.0    2150.0  13880.0   10157.0
2007 1         2824    635    3137.0     2090.0    1114.0  15859.0   11739.0
     2         2914   1747    4149.0     2843.0    1608.0  13928.0    9692.0
2008 1         2824    635    3395.0     2270.0    1210.0  15972.0   11492.0
     2         2914   1747    4039.0     2869.0    1757.0  14129.0   10048.0
2009 1         2824    635    3484.0     2270.0    1141.0  14637.0   10090.0
     2         2914   1747    4419.0     3247.0    2137.0  13637.0    9631.0
2010 1         2824    635    3103.0     2115.0    1228.0  15847.0   11768.0
     2         2914   1747    4301.0     3134.0    2059.0  14566.0   10324.0
2011 1         2824    635    3538.0     2423.0    1358.0  16101.0   11688.0
     2         2914   1747    4520.0     3218.0    2008.0  13808.0    9747.0
2012 1         2824    635    3502.0     2215.0     990.0  14114.0    9556.0
     2         2914   1747    4251.0     3091.0    1953.0  13908.0   10081.0
2013 1         2824    635    3089.0     2057.0    1023.0  15778.0   11441.0
     2         2914   1747    4554.0     3250.0    1967.0  14138.0    9664.0
2014 1         2824    635    3600.0     2495.0    1400.0  15141.0   10145.0
     2         2914   1747    4470.0     3275.0    2088.0  14656.0   10135.0
2015 1         2824    635    3639.0     2401.0    1172.0  14869.0    9631.0
     2         2914   1747    4622.0     3367.0    2115.0  14276.0    9688.0

               Min Hum  Max Vis Km  Mean Vis Km  Min Vis Km  Max Wind Km/h  \
year semester
1997 1          8188.0      1551.0       1479.0      1246.0           3301
     2          7480.0      1723.0       1607.0      1353.0           3738
1998 1          7585.0      1616.0       1551.0      1313.0           3679
     2          6252.0      1499.0       1452.0      1322.0           3489
1999 1          5982.0      1546.0       1509.0      1362.0           4196
     2          7015.0      1644.0       1567.0      1404.0           4221
2000 1          4153.0       814.0        782.0       677.0           1643
     2          6161.0      1359.0       1294.0      1095.0           3729
2001 1          7276.0      1570.0       1497.0      1235.0           4356
     2          6465.0      1487.0       1395.0      1215.0           3668
2002 1          7210.0      1539.0       1436.0      1202.0           3684
     2          7475.0      1709.0       1604.0      1315.0           3958
2003 1          6880.0      1596.0       1547.0      1354.0           4138
     2          7006.0      1631.0       1565.0      1339.0           3850
2004 1          5803.0      1371.0       1321.0      1149.0           3147
     2          6107.0      1398.0       1340.0      1172.0           3960
2005 1          5328.0      1381.0       1349.0      1241.0           4417
     2          6006.0      1401.0       1341.0      1167.0           3856
2006 1          6460.0      1594.0       1531.0      1302.0           4078
     2          6404.0      1376.0       1311.0      1114.0           3961
2007 1          7456.0      1661.0       1552.0      1295.0           4108
     2          5651.0      1314.0       1264.0      1173.0           3677
2008 1          7019.0      1581.0       1522.0      1285.0           4177
     2          6241.0      1487.0       1445.0      1298.0           4058
2009 1          5927.0      1356.0       1292.0      1112.0           4279
     2          5910.0      1334.0       1267.0      1083.0           4161
2010 1          7682.0      1630.0       1531.0      1289.0           4397
     2          6201.0      1288.0       1221.0      1050.0           3825
2011 1          7035.0      1473.0       1386.0      1162.0           3691
     2          5825.0      1194.0       1141.0      1022.0           3788
2012 1          4940.0      3078.0       2006.0      1619.0           4445
     2          5771.0      5366.0       3252.0      2633.0           4089
2013 1          6350.0      5411.0       2556.0      1823.0           4728
     2          4561.0      5659.0       3587.0      2550.0           4171
2014 1          4857.0      5585.0       3602.0      1849.0           4767
     2          4888.0      5656.0       3955.0      2264.0           4100
2015 1          4332.0      5564.0       3898.0      2346.0           4272
     2          4514.0      5518.0       3834.0      2180.0           3688

               Mean Wind Kmh
year semester
1997 1                  1275
     2                  1459
1998 1                  1584
     2                  1504
1999 1                  1727
     2                  1653
2000 1                   548
     2                  1618
2001 1                  1879
     2                  1417
2002 1                  1464
     2                  1619
2003 1                  1780
     2                  1518
2004 1                  1317
     2                  1576
2005 1                  1874
     2                  1704
2006 1                  1745
     2                  1734
2007 1                  1749
     2                  1564
2008 1                  1745
     2                  1657
2009 1                  1806
     2                  1751
2010 1                  1861
     2                  1620
2011 1                  1548
     2                  1555
2012 1                  1899
     2                  1710
2013 1                  2105
     2                  1647
2014 1                  2145
     2                  1709
2015 1                  1803
     2                  1573

In [97]:
def resetIndex(df):
    df.reset_index(inplace = True)

resetIndex(df)

In [98]:
df

,year,semester,day,month,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1997,1,2824,635,3622.0,2471.0,1413.0,15986.0,11966.0,8188.0,1551.0,1479.0,1246.0,3301,1275
1,1997,2,2914,1747,4349.0,3227.0,2184.0,14688.0,10886.0,7480.0,1723.0,1607.0,1353.0,3738,1459
2,1998,1,2824,635,3378.0,2259.0,1239.0,16016.0,11623.0,7585.0,1616.0,1551.0,1313.0,3679,1584
3,1998,2,2914,1747,4326.0,3054.0,1851.0,14365.0,10341.0,6252.0,1499.0,1452.0,1322.0,3489,1504
4,1999,1,2824,635,3394.0,2185.0,1056.0,15333.0,10484.0,5982.0,1546.0,1509.0,1362.0,4196,1727
5,1999,2,2914,1747,4093.0,3017.0,2020.0,14677.0,10889.0,7015.0,1644.0,1567.0,1404.0,4221,1653
6,2000,1,1660,347,1974.0,1267.0,607.0,8972.0,6761.0,4153.0,814.0,782.0,677.0,1643,548
7,2000,2,2533,1603,3555.0,2500.0,1580.0,13483.0,9732.0,6161.0,1359.0,1294.0,1095.0,3729,1618
8,2001,1,2824,635,3214.0,2173.0,1215.0,15377.0,11244.0,7276.0,1570.0,1497.0,1235.0,4356,1879
9,2001,2,2914,1747,3977.0,2766.0,1647.0,14322.0,10358.0,6465.0,1487.0,1395.0,1215.0,3668,1417
10,2002,1,2824,635,3333.0,2186.0,1117.0,15762.0,11378.0,7210.0,1539.0,1436.0,1202.0,3684,1464
11,2002,2,2914,1747,4032.0,2986.0,2004.0,15176.0,11365.0,7475.0,1709.0,1604.0,1315.0,3958,1619
12,2003,1,2824,635,3400.0,2292.0,1262.0,15438.0,11065.0,6880.0,1596.0,1547.0,1354.0,4138,1780
13,2003,2,2914,1747,4146.0,3056.0,2036.0,14338.0,10653.0,7006.0,1631.0,1565.0,1339.0,3850,1518
14,2004,1,2329,605,2794.0,1879.0,1023.0,12964.0,9381.0,5803.0,1371.0,1321.0,1149.0,3147,1317
15,2004,2,2914,1747,4282.0,3071.0,1923.0,14176.0,10090.0,6107.0,1398.0,1340.0,1172.0,3960,1576
16,2005,1,2824,635,3526.0,2253.0,1070.0,13818.0,9485.0,5328.0,1381.0,1349.0,1241.0,4417,1874
17,2005,2,2914,1747,4210.0,3027.0,1907.0,13200.0,9561.0,6006.0,1401.0,1341.0,1167.0,3856,1704
18,2006,1,2824,635,3459.0,2286.0,1200.0,14973.0,10626.0,6460.0,1594.0,1531.0,1302.0,4078,1745
19,2006,2,2914,1747,4357.0,3199.0,2150.0,13880.0,10157.0,6404.0,1376.0,1311.0,1114.0,3961,1734
20,2007,1,2824,635,3137.0,2090.0,1114.0,15859.0,11739.0,7456.0,1661.0,1552.0,1295.0,4108,1749
21,2007,2,2914,1747,4149.0,2843.0,1608.0,13928.0,9692.0,5651.0,1314.0,1264.0,1173.0,3677,1564
22,2008,1,2824,635,3395.0,2270.0,1210.0,15972.0,11492.0,7019.0,1581.0,1522.0,1285.0,4177,1745
23,2008,2,2914,1747,4039.0,2869.0,1757.0,14129.0,10048.0,6241.0,1487.0,1445.0,1298.0,4058,1657
24,2009,1,2824,635,3484.0,2270.0,1141.0,14637.0,10090.0,5927.0,1356.0,1292.0,1112.0,4279,1806
25,2009,2,2914,1747,4419.0,3247.0,2137.0,13637.0,9631.0,5910.0,1334.0,1267.0,1083.0,4161,1751
26,2010,1,2824,635,3103.0,2115.0,1228.0,15847.0,11768.0,7682.0,1630.0,1531.0,1289.0,4397,1861
27,2010,2,2914,1747,4301.0,3134.0,2059.0,14566.0,10324.0,6201.0,1288.0,1221.0,1050.0,3825,1620
28,2011,1,2824,635,3538.0,2423.0,1358.0,16101.0,11688.0,7035.0,1473.0,1386.0,1162.0,3691,1548
29,2011,2,2914,1747,4520.0,3218.0,2008.0,13808.0,9747.0,5825.0,1194.0,1141.0,1022.0,3788,1555
30,2012,1,2824,635,3502.0,2215.0,990.0,14114.0,9556.0,4940.0,3078.0,2006.0,1619.0,4445,1899
31,2012,2,2914,1747,4251.0,3091.0,1953.0,13908.0,10081.0,5771.0,5366.0,3252.0,2633.0,4089,1710
32,2013,1,2824,635,3089.0,2057.0,1023.0,15778.0,11441.0,6350.0,5411.0,2556.0,1823.0,4728,2105
33,2013,2,2914,1747,4554.0,3250.0,1967.0,14138.0,9664.0,4561.0,5659.0,3587.0,2550.0,4171,1647
34,2014,1,2824,635,3600.0,2495.0,1400.0,15141.0,10145.0,4857.0,5585.0,3602.0,1849.0,4767,2145
35,2014,2,2914,1747,4470.0,3275.0,2088.0,14656.0,10135.0,4888.0,5656.0,3955.0,2264.0,4100,1709
36,2015,1,2824,635,3639.0,2401.0,1172.0,14869.0,9631.0,4332.0,5564.0,3898.0,2346.0,4272,1803
37,2015,2,2914,1747,4622.0,3367.0,2115.0,14276.0,9688.0,4514.0,5518.0,3834.0,2180.0,3688,1573

In [99]:
df.columns

Index(['year', 'semester', 'day', 'month', 'Max Temp', 'Mean Temp', 'Min Temp',
       'Max Hum', 'Mean Hum', 'Min Hum', 'Max Vis Km', 'Mean Vis Km',
       'Min Vis Km', 'Max Wind Km/h', 'Mean Wind Kmh'],
      dtype='object')

In [100]:
df[['day', 'month', 'Max Temp', 'Mean Temp', 'Min Temp',
       'Max Hum', 'Mean Hum', 'Min Hum', 'Max Vis Km', 'Mean Vis Km',
       'Min Vis Km', 'Max Wind Km/h', 'Mean Wind Kmh']]=df[['day', 'month', 'Max Temp', 'Mean Temp', 'Min Temp',
       'Max Hum', 'Mean Hum', 'Min Hum', 'Max Vis Km', 'Mean Vis Km',
       'Min Vis Km', 'Max Wind Km/h', 'Mean Wind Kmh']].apply(lambda x: x/182.5)

In [101]:
df

,year,semester,day,month,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1997,1,15.473973,3.479452,19.846575,13.539726,7.742466,87.594521,65.567123,44.865753,8.498630,8.104110,6.827397,18.087671,6.986301
1,1997,2,15.967123,9.572603,23.830137,17.682192,11.967123,80.482192,59.649315,40.986301,9.441096,8.805479,7.413699,20.482192,7.994521
2,1998,1,15.473973,3.479452,18.509589,12.378082,6.789041,87.758904,63.687671,41.561644,8.854795,8.498630,7.194521,20.158904,8.679452
3,1998,2,15.967123,9.572603,23.704110,16.734247,10.142466,78.712329,56.663014,34.257534,8.213699,7.956164,7.243836,19.117808,8.241096
4,1999,1,15.473973,3.479452,18.597260,11.972603,5.786301,84.016438,57.446575,32.778082,8.471233,8.268493,7.463014,22.991781,9.463014
5,1999,2,15.967123,9.572603,22.427397,16.531507,11.068493,80.421918,59.665753,38.438356,9.008219,8.586301,7.693151,23.128767,9.057534
6,2000,1,9.095890,1.901370,10.816438,6.942466,3.326027,49.161644,37.046575,22.756164,4.460274,4.284932,3.709589,9.002740,3.002740
7,2000,2,13.879452,8.783562,19.479452,13.698630,8.657534,73.879452,53.326027,33.758904,7.446575,7.090411,6.000000,20.432877,8.865753
8,2001,1,15.473973,3.479452,17.610959,11.906849,6.657534,84.257534,61.610959,39.868493,8.602740,8.202740,6.767123,23.868493,10.295890
9,2001,2,15.967123,9.572603,21.791781,15.156164,9.024658,78.476712,56.756164,35.424658,8.147945,7.643836,6.657534,20.098630,7.764384
10,2002,1,15.473973,3.479452,18.263014,11.978082,6.120548,86.367123,62.345205,39.506849,8.432877,7.868493,6.586301,20.186301,8.021918
11,2002,2,15.967123,9.572603,22.093151,16.361644,10.980822,83.156164,62.273973,40.958904,9.364384,8.789041,7.205479,21.687671,8.871233
12,2003,1,15.473973,3.479452,18.630137,12.558904,6.915068,84.591781,60.630137,37.698630,8.745205,8.476712,7.419178,22.673973,9.753425
13,2003,2,15.967123,9.572603,22.717808,16.745205,11.156164,78.564384,58.372603,38.389041,8.936986,8.575342,7.336986,21.095890,8.317808
14,2004,1,12.761644,3.315068,15.309589,10.295890,5.605479,71.035616,51.402740,31.797260,7.512329,7.238356,6.295890,17.243836,7.216438
15,2004,2,15.967123,9.572603,23.463014,16.827397,10.536986,77.676712,55.287671,33.463014,7.660274,7.342466,6.421918,21.698630,8.635616
16,2005,1,15.473973,3.479452,19.320548,12.345205,5.863014,75.715068,51.972603,29.194521,7.567123,7.391781,6.800000,24.202740,10.268493
17,2005,2,15.967123,9.572603,23.068493,16.586301,10.449315,72.328767,52.389041,32.909589,7.676712,7.347945,6.394521,21.128767,9.336986
18,2006,1,15.473973,3.479452,18.953425,12.526027,6.575342,82.043836,58.224658,35.397260,8.734247,8.389041,7.134247,22.345205,9.561644
19,2006,2,15.967123,9.572603,23.873973,17.528767,11.780822,76.054795,55.654795,35.090411,7.539726,7.183562,6.104110,21.704110,9.501370
20,2007,1,15.473973,3.479452,17.189041,11.452055,6.104110,86.898630,64.323288,40.854795,9.101370,8.504110,7.095890,22.509589,9.583562
21,2007,2,15.967123,9.572603,22.734247,15.578082,8.810959,76.317808,53.106849,30.964384,7.200000,6.926027,6.427397,20.147945,8.569863
22,2008,1,15.473973,3.479452,18.602740,12.438356,6.630137,87.517808,62.969863,38.460274,8.663014,8.339726,7.041096,22.887671,9.561644
23,2008,2,15.967123,9.572603,22.131507,15.720548,9.627397,77.419178,55.057534,34.197260,8.147945,7.917808,7.112329,22.235616,9.079452
24,2009,1,15.473973,3.479452,19.090411,12.438356,6.252055,80.202740,55.287671,32.476712,7.430137,7.079452,6.093151,23.446575,9.895890
25,2009,2,15.967123,9.572603,24.213699,17.791781,11.709589,74.723288,52.772603,32.383562,7.309589,6.942466,5.934247,22.800000,9.594521
26,2010,1,15.473973,3.479452,17.002740,11.589041,6.728767,86.832877,64.482192,42.093151,8.931507,8.389041,7.063014,24.093151,10.197260
27,2010,2,15.967123,9.572603,23.567123,17.172603,11.282192,79.813699,56.569863,33.978082,7.057534,6.690411,5.753425,20.958904,8.876712
28,2011,1,15.473973,3.479452,19.386301,13.276712,7.441096,88.224658,64.043836,38.547945,8.071233,7.594521,6.367123,20.224658,8.482192
29,2011,2,15.967123,9.572603,24.767123,17.632877,11.002740,75.660274,53.408219,31.917808,6.542466,6.252055,5.600000,20.756164,8.520548
30,2012,1,15.473973,3.479452,19.189041,12.136986,5.424658,77.336986,52.361644,27.068493,16.865753,10.991781,8.871233,24.356164,10.405479
31,2012,2,15.967123,9.572603,23.293151,16.936986,10.701370,76.208219,55.238356,31.621918,29.402740,17.819178,14.427397,22.405479,9.369863
32,2013,1,15.473973,3.479452,16.926027,11.271233,5.605479,86.454795,62.690411,34.794521,29.649315,14.005479,9.989041,25.906849,11.534247
33,2013,2,15.967123,9.572603,24.953425,17.808219,10.778082,77.468493,52.953425,24.991781,31.008219,19.654795,13.972603,22.854795,9.024658
34,2014,1,15.473973,3.479452,19.726027,13.671233,7.671233,82.964384,55.589041,26.613699,30.602740,19.736986,10.131507,26.120548,11.753425
35,2014,2,15.967123,9.572603,24.493151,17.945205,11.441096,80.306849,55.534247,26.783562,30.991781,21.671233,12.405479,22.465753,9.364384
36,2015,1,15.473973,3.479452,19.939726,13.156164,6.421918,81.473973,52.772603,23.736986,30.487671,21.358904,12.854795,23.408219,9.879452
37,2015,2,15.967123,9.572603,25.326027,18.449315,11.589041,78.224658,53.084932,24.734247,30.235616,21.008219,11.945205,20.208219,8.619178

In [102]:
df = round(df,2)

In [103]:
df

,year,semester,day,month,Max Temp,Mean Temp,Min Temp,Max Hum,Mean Hum,Min Hum,Max Vis Km,Mean Vis Km,Min Vis Km,Max Wind Km/h,Mean Wind Kmh
0,1997,1,15.47,3.48,19.85,13.54,7.74,87.59,65.57,44.87,8.50,8.10,6.83,18.09,6.99
1,1997,2,15.97,9.57,23.83,17.68,11.97,80.48,59.65,40.99,9.44,8.81,7.41,20.48,7.99
2,1998,1,15.47,3.48,18.51,12.38,6.79,87.76,63.69,41.56,8.85,8.50,7.19,20.16,8.68
3,1998,2,15.97,9.57,23.70,16.73,10.14,78.71,56.66,34.26,8.21,7.96,7.24,19.12,8.24
4,1999,1,15.47,3.48,18.60,11.97,5.79,84.02,57.45,32.78,8.47,8.27,7.46,22.99,9.46
5,1999,2,15.97,9.57,22.43,16.53,11.07,80.42,59.67,38.44,9.01,8.59,7.69,23.13,9.06
6,2000,1,9.10,1.90,10.82,6.94,3.33,49.16,37.05,22.76,4.46,4.28,3.71,9.00,3.00
7,2000,2,13.88,8.78,19.48,13.70,8.66,73.88,53.33,33.76,7.45,7.09,6.00,20.43,8.87
8,2001,1,15.47,3.48,17.61,11.91,6.66,84.26,61.61,39.87,8.60,8.20,6.77,23.87,10.30
9,2001,2,15.97,9.57,21.79,15.16,9.02,78.48,56.76,35.42,8.15,7.64,6.66,20.10,7.76
10,2002,1,15.47,3.48,18.26,11.98,6.12,86.37,62.35,39.51,8.43,7.87,6.59,20.19,8.02
11,2002,2,15.97,9.57,22.09,16.36,10.98,83.16,62.27,40.96,9.36,8.79,7.21,21.69,8.87
12,2003,1,15.47,3.48,18.63,12.56,6.92,84.59,60.63,37.70,8.75,8.48,7.42,22.67,9.75
13,2003,2,15.97,9.57,22.72,16.75,11.16,78.56,58.37,38.39,8.94,8.58,7.34,21.10,8.32
14,2004,1,12.76,3.32,15.31,10.30,5.61,71.04,51.40,31.80,7.51,7.24,6.30,17.24,7.22
15,2004,2,15.97,9.57,23.46,16.83,10.54,77.68,55.29,33.46,7.66,7.34,6.42,21.70,8.64
16,2005,1,15.47,3.48,19.32,12.35,5.86,75.72,51.97,29.19,7.57,7.39,6.80,24.20,10.27
17,2005,2,15.97,9.57,23.07,16.59,10.45,72.33,52.39,32.91,7.68,7.35,6.39,21.13,9.34
18,2006,1,15.47,3.48,18.95,12.53,6.58,82.04,58.22,35.40,8.73,8.39,7.13,22.35,9.56
19,2006,2,15.97,9.57,23.87,17.53,11.78,76.05,55.65,35.09,7.54,7.18,6.10,21.70,9.50
20,2007,1,15.47,3.48,17.19,11.45,6.10,86.90,64.32,40.85,9.10,8.50,7.10,22.51,9.58
21,2007,2,15.97,9.57,22.73,15.58,8.81,76.32,53.11,30.96,7.20,6.93,6.43,20.15,8.57
22,2008,1,15.47,3.48,18.60,12.44,6.63,87.52,62.97,38.46,8.66,8.34,7.04,22.89,9.56
23,2008,2,15.97,9.57,22.13,15.72,9.63,77.42,55.06,34.20,8.15,7.92,7.11,22.24,9.08
24,2009,1,15.47,3.48,19.09,12.44,6.25,80.20,55.29,32.48,7.43,7.08,6.09,23.45,9.90
25,2009,2,15.97,9.57,24.21,17.79,11.71,74.72,52.77,32.38,7.31,6.94,5.93,22.80,9.59
26,2010,1,15.47,3.48,17.00,11.59,6.73,86.83,64.48,42.09,8.93,8.39,7.06,24.09,10.20
27,2010,2,15.97,9.57,23.57,17.17,11.28,79.81,56.57,33.98,7.06,6.69,5.75,20.96,8.88
28,2011,1,15.47,3.48,19.39,13.28,7.44,88.22,64.04,38.55,8.07,7.59,6.37,20.22,8.48
29,2011,2,15.97,9.57,24.77,17.63,11.00,75.66,53.41,31.92,6.54,6.25,5.60,20.76,8.52
30,2012,1,15.47,3.48,19.19,12.14,5.42,77.34,52.36,27.07,16.87,10.99,8.87,24.36,10.41
31,2012,2,15.97,9.57,23.29,16.94,10.70,76.21,55.24,31.62,29.40,17.82,14.43,22.41,9.37
32,2013,1,15.47,3.48,16.93,11.27,5.61,86.45,62.69,34.79,29.65,14.01,9.99,25.91,11.53
33,2013,2,15.97,9.57,24.95,17.81,10.78,77.47,52.95,24.99,31.01,19.65,13.97,22.85,9.02
34,2014,1,15.47,3.48,19.73,13.67,7.67,82.96,55.59,26.61,30.60,19.74,10.13,26.12,11.75
35,2014,2,15.97,9.57,24.49,17.95,11.44,80.31,55.53,26.78,30.99,21.67,12.41,22.47,9.36
36,2015,1,15.47,3.48,19.94,13.16,6.42,81.47,52.77,23.74,30.49,21.36,12.85,23.41,9.88
37,2015,2,15.97,9.57,25.33,18.45,11.59,78.22,53.08,24.73,30.24,21.01,11.95,20.21,8.62

In [104]:
df.dtypes

year                int64
semester         category
day               float64
month             float64
Max Temp          float64
Mean Temp         float64
Min Temp          float64
Max Hum           float64
Mean Hum          float64
Min Hum           float64
Max Vis Km        float64
Mean Vis Km       float64
Min Vis Km        float64
Max Wind Km/h     float64
Mean Wind Kmh     float64
dtype: object

In [ ]:
df.shape

In [ ]:
df = df.astype({"semester": int})

In [105]:
df.to_csv('good_weatherrr.csv')